server:
    max_connections: 4000
    host: localhost
    port: 3000

ekg:
    host: 192.168.33.10
    port: 3001

client:
    spawn_threads: 1000 # (10.7%, 13sec)
#    spawn_threads: 2000 # (23%, 16sec) (27%, 16sec)
#    spawn_threads: 3000 # (43%, 24sec) (46%, 24sec)
#    spawn_threads: 4000 # (57%? 33sec)
